### ISSUE TITLE
Apply tags to resources based on a variable in variables.tf

### ISSUE THREAD

**Issue by sjmiller609** [astronomer/terraform-aws-astronomer-aws#4]
Add a variable called 'tags' of type map. Merge those tags with deployment_id, in a local variable in locals.tf. Make use of the 'tags' argument in the RDS, VPC, and EKS modules. Sometime you have to merge the local.tags with other tags, for instance in the case of the VPC, where kubernetes-specific tags will be required. For resources created outside of modules (bastion, security groups, etc.), add the tags if the terraform resource supports them. Not all AWS resources support tags, so it's ok to skip where it's not supported.

Here is an example of how terraform map type can be merged
```
tags        = "${merge(var.tags, map("Name", "${var.cluster_name}-eks_cluster_sg"))}"
```

**Comment by ianstanton** [comment]
Quotes from customer for reference:
> It would be lovely we could specify an array of tags in the terraform variables file when bringing up a new installation. Those tags would be applied to all the various pieces of infrastructure that terraform creates. This would enable easy cost accounting on how much each cluster is costing.

> This would be support for arguments tags and volume_tags for aws_instance in terraform: https://www.terraform.io/docs/providers/aws/r/instance.html.

**Comment by ianstanton** [comment]
Quotes form customer for reference:
> It would be lovely we could specify an array of tags in the terraform variables file when bringing up a new installation. Those tags would be applied to all the various pieces of infrastructure that terraform creates. This would enable easy cost accounting on how much each cluster is costing.

> This would be support for arguments tags and volume_tags for aws_instance in terraform: https://www.terraform.io/docs/providers/aws/r/instance.html.

**Comment by ianstanton** [comment]
Quotes form customer for reference:
> It would be lovely we could specify an array of tags in the terraform variables file when bringing up a new installation. Those tags would be applied to all the various pieces of infrastructure that terraform creates. This would enable easy cost accounting on how much each cluster is costing.

> This would be support for arguments tags and volume_tags for aws_instance in terraform: https://www.terraform.io/docs/providers/aws/r/instance.html.

**Comment by ianstanton** [comment]
Quotes form customer for reference:
> It would be lovely we could specify an array of tags in the terraform variables file when bringing up a new installation. Those tags would be applied to all the various pieces of infrastructure that terraform creates. This would enable easy cost accounting on how much each cluster is costing.

> This would be support for arguments tags and volume_tags for aws_instance in terraform: https://www.terraform.io/docs/providers/aws/r/instance.html.

**Comment by ianstanton** [comment]
Successfully tagged EKS resources:
* In `locals.tf`:
 ```
  tags = "${map(
    "Deployment ID", "${var.deployment_id}"
  )}"
 ```
* In `variables.tf`:
```
variable "tags" {
  description = "A map of tags to add to all resources."
  type        = map(string)
  default     = {}
}
```
* In resource file (`eks.tf` in this case):
```
  tags = "${merge(
    local.tags,
    map(
      "Deployment ID", "${var.deployment_id}"
    )
  )}"
```

**Comment by sjmiller609** [comment]
closed by Ian's https://github.com/astronomer/terraform-aws-astronomer-aws/pull/7
