### ISSUE TITLE
CI testing

### ISSUE THREAD

**Issue by sjmiller609** [astronomer/terraform-aws-astronomer-aws#9]
1 and 2 may run simultaneously

1)
- terraform apply to deploy from scratch
- run python system testing in the form of python unit tests. For this issue, don't go overboard, just keep it simple like a check that the database and the EKS cluster exist using boto3, use testinfra to check that tinyproxy is running on port 8888 of the bastion. This just serves as an outline for adding additional tests. This way other developers can reference these examples when they add more tests. eventually we will want to add comprehensive testing, especially around security groups and networks, but not for the sake of this issue.
- terraform destroy

2)

EDIT, new plan:
- terraform apply the previous, working version (most recent version from terraform registry)
- terraform apply
- require a major version update on this module if any resources (or a list of important resources?) have interrupting updates.
- run system tests
- terraform destroy

deprecated, ignore:
```
- terraform apply the previous, working version (most recent version from terraform registry)
- terraform apply the most recent terraform-kubernetes-astronomer-system-components
- terraform apply the most recent terraform-kubernetes-astronomer
- start black-box monitoring. reuse the blackbox monitoring from the CI testing of terraform-kubernetes-astronomer https://github.com/astronomer/terraform-kubernetes-astronomer/issues/5
- terraform apply this version
- the cluster must return to a healthy state automatically. if an interrupt of the black-box testing occurs, then it should be timed on how long it took to come back up, and we will require a major version update on this module.
```

I also think we should use behave testing for this, same as this issue https://github.com/astronomer/terraform-kubernetes-astronomer/issues/5

The below is a very rough outline

Given AWS credentials in the CI account
When terraform is applied
Then python system testing passes
When terraform is destroyed

EDIT:

Given AWS credentials in the CI account
When the most recent version is applied
And terraform is applied
And if there was an interrupt on important resources, then require a major version upgrade
When terraform is destroyed

Deprecated, ignore:
```
Given AWS credentials in the CI account
When the most recent version is applied
And the latest system components are applied
And the latest astronomer is applied
And black-box testing is enabled
And terraform is applied
Then the black-box testing experienced less than 30 minutes of interruption
When terraform is destroyed
Then if there was downtime greater than 10 seconds, require a major version upgrade
```

**Comment by sjmiller609** [comment]
We also will want to nuke the whole CI account at the end of CI testing. I have a script to nuke an AWS account.

**Comment by sjmiller609** [comment]
@kaxil I'm interested to hear your input on this one

**Comment by kaxil** [comment]
Just for future reference:

* https://testinfra.readthedocs.io/en/latest/
* https://boto3.amazonaws.com/v1/documentation/api/latest/index.html?id=docs_gateway
* https://tinyproxy.github.io/

**Comment by kaxil** [comment]
@sjmiller609

Agreed on (1)

 For (2) Shouldn't it just trigger the downstream pipeline (terraform-aws-astronomer-cloud or something) that would take the master of this repo and create infra and deploy astro?

**Comment by sjmiller609** [comment]
@kaxil Good call. It should trigger terraform-aws-astronomer-enterprise and terraform-aws-astronomer-private-cloud. The major version upgrades on those modules can indicate black-box downtime. On this repo, we should do a major version upgrade if any resource has an interrupting update, i.e. -/+ vs ~ ?

**Comment by sjmiller609** [comment]
There is a pipeline in place now, but it does not have all the features specified above yet https://cloud.drone.io/astronomer/terraform-aws-astronomer-aws

**Comment by sjmiller609** [comment]
there is also a module and pipeline for enterprise from-scratch deployment https://cloud.drone.io/astronomer/terraform-aws-astronomer-enterprise
